name: update-dotnet-sdk

on:

  # Scheduled trigger to check for .NET SDK updates at 12 UTC every Monday
  schedule:
    - cron:  '00 12 * * MON'

  # Manual trigger to update the .NET SDK on-demand.
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: martincostello/update-dotnet-sdk@caa37bca20d50c57dc0173d77f956751bb1a1d55 # v3.2.1
      with:
        quality: 'daily'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
