name: update-dotnet-sdk

on:

  # Scheduled trigger to check for .NET SDK updates at 12 UTC every Monday
  schedule:
    - cron:  '00 12 * * MON'

  # Manual trigger to update the .NET SDK on-demand.
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: martincostello/update-dotnet-sdk@b5684309b4d6dd59ee955b150f5632c5f3a59f79 # v3.1.4
      with:
        quality: 'daily'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
